apiVersion: v1
kind: Secret
metadata:
  name: existing-secret
stringData:
  existing-key: existing-value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: merge-policies
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: fake1
    kind: ClusterSecretStore
  target:
    name: existing-secret
    creationPolicy: Merge
    deletionPolicy: Merge
  data:
  - secretKey:  fake-1-key
    sourceRef:
      storeRef:
        name:  fake1
        kind: ClusterSecretStore
    remoteRef:
      key: "/foo/hello"
  - secretKey:  fake-2-key
    remoteRef:
      key: "/bar/hello"
    sourceRef:
      storeRef:
        name:  fake2
        kind: ClusterSecretStore
