apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake1
spec:
  provider:
    fake:
      data:
      - key: "/foo/hello"
        value: "HELLO"
      - key: "/foo/how"
        value: "HOW_ARE_YOU"
      - key: "/foo/good"
        value: "GOOD_THANKS"
      - key: "/foo/bye"
        value: "GOODBYE"
      - key: "/foo/user"
        value: '{"username": "my-user", "password": "pass"}'
--- 
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake2
spec:
  provider:
    fake:
      data:
      - key: "/bar/hello"
        value: "hello_fake2"
      - key: "/bar/how"
        value: "how_are_you_fake2"
      - key: "/bar/good"
        value: "good_thanks_fake2"
      - key: "/bar/bye"
        value: "bye_fake2"
      - key: "/bar/user"
        value: '{"username": "eyJ1c2VybmFtZSI6ICJ1c2VyIiwgInBhc3N3b3JkIjogInBhc3MifQ==", "password": "czNjdXIzX3A0c3M="}'
